import json
import time

current_time = time.time() - 3600 # 1 hour ago default

strategies = [
    {
        "id": "A",
        "title": "【時事・経済】「中学生でもわかるニュース図解」",
        "genre": "時事・政治・経済",
        "platforms": ["X", "Note"],
        "persona": "ニュースを追う時間はないが社会の動きを知っておきたい20〜30代のビジネスパーソン、就活生。",
        "approach": "複雑な時事問題（政治資金、円安など）を4枚の図解インフォグラフィックで解説。深掘りした論考をNoteへ。",
        "reasoning": "Xでは「図解」「まとめ」のブックマーク率が高くバズりやすい。",
        "estimated_revenue": "月5万円〜（X Premiumインプレッション収益＋Note課金）",
        "required_cost": "画像生成/デザインツール（Canva等・月額千円程度）",
        "reviews": { "マネージャーAI": "Xのアルゴリズムとの親和性が最も高く即効性がある。", "リスクマネージャーAI": "思想の偏りが出ると炎上するため中立性が必須。" },
        "score": 5, "status": "最優先検証",
        "updates": {}
    },
    {
        "id": "B",
        "title": "【健康・美容】「ズボラ人間向け・1日3分の〇〇」",
        "genre": "健康・美容",
        "platforms": ["YouTube", "Note"],
        "persona": "毎日忙しく、お金や手間をかけずに自己投資したい20〜40代の男女。",
        "approach": "超ハードルが低い健康・美容法をショート動画で配信。詳細なルーティンやおすすめアイテム一覧をNoteで公開。",
        "reasoning": "「タイパ」重視のトレンド。ヘルスケア・美容系は広告単価もアフィ単価も高く普遍的需要がある。",
        "estimated_revenue": "月10万円〜（アフィリエイト報酬、YouTube収益）",
        "required_cost": "動画編集ソフト、検証用商品の購入費（月数千円〜）",
        "reviews": { "グロースAI": "Shortsからの異プラットフォーム誘導は歩留まりが課題ですが強力です。" },
        "score": 5, "status": "最優先検証",
        "updates": {}
    },
    {
        "id": "C",
        "title": "【旅行・お出かけ】「週末の隠れ家・穴場スポット」",
        "genre": "旅行・お出かけ",
        "platforms": ["X", "YouTube"],
        "persona": "週末の予定や子連れのお出かけ先を探している20〜40代。",
        "approach": "「実は〇〇にある…」「コスパ最強の宿」などのフックで画像を展開し、旅行予約サイトへ誘導。",
        "reasoning": "国内旅行需要・インバウンド好調。「穴場」「お得」のキーワードが強く刺さる。",
        "estimated_revenue": "月15万円〜（旅行系高単価アフィリエイト）",
        "required_cost": "本人による取材費用、もしくはUGC掲載許可取りの手間。",
        "reviews": { "クリエイターAI": "低コストな方法から始めるべきです。" },
        "score": 4, "status": "保留・次点",
        "updates": {}
    },
    {
        "id": "D",
        "title": "【地政学・戦争】「5分でわかる世界の紛争地域」",
        "genre": "戦争・地政学",
        "platforms": ["YouTube"],
        "persona": "世界情勢に不安を感じ、歴史的背景からニュースを深く理解したい層。",
        "approach": "地図と歴史解説を用いたアニメーション形式の解説動画。メンバーシップで特定地域の深掘り。",
        "reasoning": "防衛や世界情勢への関心が歴史的に高まっており、解説系教育コンテンツのRPMが高い。",
        "estimated_revenue": "月20万円〜（YouTube広告、メンバーシップ）",
        "required_cost": "動画編集・アニメーション制作ソフト、専門書・論文などの調査費。",
        "reviews": { "リスクマネージャーAI": "センシティブなトピックのため、YouTubeの広告剥がしリスクに注意が必要です。" },
        "score": 4, "status": "検証中",
        "updates": {}
    },
    {
        "id": "E",
        "title": "【スポーツ】「データで見る！〇〇リーグ・戦術解説」",
        "genre": "スポーツ",
        "platforms": ["X", "Note"],
        "persona": "週末の試合観戦が趣味で、一歩踏み込んだ戦術的視点を好むスポーツファン。",
        "approach": "直近の試合のスタッツやポジショニングデータを図表化してXで連投。詳細な戦術分析をNoteで。",
        "reasoning": "コアファンのコミュニティは熱量が高く、Noteの有料購読に繋がりやすい。",
        "estimated_revenue": "月8万円〜",
        "required_cost": "試合中継のサブスクリプション費用、データ分析ツール。",
        "reviews": { "アナリストAI": "ニッチですが、確実な固定ファンがつきます。" },
        "score": 3, "status": "保留・次点",
        "updates": {}
    },
    {
        "id": "F",
        "title": "【ゲーム】「新作ゲーム・ガチ検証＆攻略最前線」",
        "genre": "ゲーム",
        "platforms": ["YouTube", "X"],
        "persona": "効率的にゲームをプレイしたいゲーマー、新作情報を追う10〜30代。",
        "approach": "発売直後の「最強武器」「最速レベル上げ」などの検証動画を最速で上げ、Xで切り抜きを拡散。",
        "reasoning": "トレンドゲームの発売直後の検索ボリューム爆発に乗ることで初期ブーストが可能。",
        "estimated_revenue": "月15万円〜",
        "required_cost": "新作ゲーム購入費、キャプチャーボードなど配信機材。",
        "reviews": { "マーケターAI": "スピード勝負になるため、専業でないと厳しい可能性があります。" },
        "score": 4, "status": "検証中",
        "updates": {}
    },
    {
        "id": "G",
        "title": "【テクノロジー・AI】「明日から使えるAI業務<br>効率化」",
        "genre": "テクノロジー・AI",
        "platforms": ["Note", "X"],
        "persona": "業務を自動化・効率化したいが、プロンプトエンジニアリングが分からない非エンジニア。",
        "approach": "具体的なプロンプトのコピペ集や、ChatGPT/Claudeの裏技をXで発信。プロンプト集をNoteで販売。",
        "reasoning": "AIの実用化フェーズに入り「どう使うか」のhow-to需要が法人・個人ともに急増。",
        "estimated_revenue": "月30万円〜（商材販売）",
        "required_cost": "AIツールの有料課金（ChatGPT Plus等）。",
        "reviews": { "グロースAI": "現在のトレンドど真ん中であり、Noteの販売益が非常に見込めます。" },
        "score": 5, "status": "最優先検証",
        "updates": {}
    },
    {
        "id": "H",
        "title": "【ペット・動物】「癒やし度MAX・動物のおもしろ生態」",
        "genre": "ペット・動物",
        "platforms": ["YouTube", "X"],
        "persona": "日常に疲れて癒やしを求めている全年齢層。",
        "approach": "著作権フリー、もしくは許可を得たかわいい動物動画に、ユニークなアテレコや生態解説を追加。",
        "reasoning": "言語の壁を超えやすいため、海外からのインプレッションも獲得可能。バズの確率が高い。",
        "estimated_revenue": "月10万円〜",
        "required_cost": "動画収集の工数。",
        "reviews": { "クリエイターAI": "オリジナルで犬猫を飼うのが最もリスクが低いですが、難しい場合はUGC活用になります。" },
        "score": 3, "status": "保留・次点",
        "updates": {}
    },
    {
        "id": "I",
        "title": "【投資・節約】「手取り20万からの新NISA＆ポイ活」",
        "genre": "投資・節約",
        "platforms": ["X", "Note"],
        "persona": "将来の資金不安はあるが、投資の知識がない20〜30代の会社員。",
        "approach": "毎月の家計簿公開や、楽天・SBI等の証券口座開設方法、ポイ活用ルートの図解。",
        "reasoning": "金融系（クレジットカード、証券口座）のアフィリエイト単価はトップクラスに高い。",
        "estimated_revenue": "月50万円〜",
        "required_cost": "なし（自身の経験）。",
        "reviews": { "アナリストAI": "競合は多いですが、1件のコンバージョン単価が1万円を超えるため魅力的です。" },
        "score": 5, "status": "最優先検証",
        "updates": {}
    },
    {
        "id": "J",
        "title": "【料理・グルメ】「100円で出来る！絶品・虚無レシピ」",
        "genre": "料理・グルメ",
        "platforms": ["YouTube", "X"],
        "persona": "一人暮らしの学生や新社会人、自炊が面倒な人。",
        "approach": "包丁を使わない、電子レンジだけで完結するような極限までハードルを下げた調理動画。",
        "reasoning": "物価高騰と時短需要のダブルパンチで、「安くて簡単」なレシピの再生数が安定している。",
        "estimated_revenue": "月8万円〜",
        "required_cost": "食材費（極少）。",
        "reviews": { "マーケターAI": "レシピ本出版や企業タイアップなどの横展開がしやすいジャンルです。" },
        "score": 4, "status": "検証中",
        "updates": {}
    },
    {
        "id": "K",
        "title": "【ライフハック】「100均・無印の隠れた名品紹介」",
        "genre": "ライフハック",
        "platforms": ["YouTube", "Note"],
        "persona": "生活の質を少し上げたい主婦層、一人暮らし層。",
        "approach": "100円ショップや無印良品の活用法、意外な使い道を紹介。Amazonアソシエイトへ誘導。",
        "reasoning": "購入ハードルが低いため、動画を見た勢いで商品を購入・試すアクションに繋がりやすい。",
        "estimated_revenue": "月7万円〜",
        "required_cost": "商品購入費。",
        "reviews": { "マネージャーAI": "コツコツと継続することで資産化しやすい無難なプランです。" },
        "score": 3, "status": "保留・次点",
        "updates": {}
    },
    {
        "id": "L",
        "title": "【エンタメ】「推し活女子のための遠征費捻出術」",
        "genre": "エンタメ",
        "platforms": ["X"],
        "persona": "アイドルやアニメキャラなどの「推し活」にお金を使いたいが金欠な10〜20代女性。",
        "approach": "短期バイトや副業、フリマアプリ活用術など「推しのために稼ぐ」に特化したノウハウ発信。",
        "reasoning": "推し活市場は急拡大中。明確な目的（推しのため）があるため、行動（副業登録等）を起こしやすい。",
        "estimated_revenue": "月15万円〜（副業紹介アフィリエイト）",
        "required_cost": "特になし。",
        "reviews": { "グロースAI": "ターゲット層の熱量が異常に高いため、SNS共有されやすいです。" },
        "score": 4, "status": "検証中",
        "updates": {}
    },
    {
        "id": "M",
        "title": "【キャリア・転職】「ブラック企業からホワイトへの脱出記」",
        "genre": "キャリア",
        "platforms": ["Note", "X"],
        "persona": "現在の職場に不満を持つが、転職に踏み切れない20代後半〜30代。",
        "approach": "自身の転職失敗談や、面接でのキラーフレーズ、年収交渉のやり方を連載。転職サイトへ誘導。",
        "reasoning": "人材系のアフィリエイト単価が高く、また「退職代行」などのニッチなアフィリエイトも絡められる。",
        "estimated_revenue": "月20万円〜",
        "required_cost": "特になし。",
        "reviews": { "アナリストAI": "春や秋の転職シーズンに大きくPVが跳ねる傾向があります。" },
        "score": 4, "status": "検証中",
        "updates": {}
    },
    {
        "id": "N",
        "title": "【学習・教育】「大人のやり直し英語・1日1フレーズ」",
        "genre": "学習・教育",
        "platforms": ["X", "YouTube"],
        "persona": "英語コンプレックスがあるが、スクールに通う時間やお金がない大人。",
        "approach": "海外ニュースや映画のワンシーンから実用的なフレーズを切り取り、毎日1つ紹介。",
        "reasoning": "自己啓発ジャンルとして普遍的。最終的に英会話スクールの無料体験等のアフィリエイトに繋げやすい。",
        "estimated_revenue": "月10万円〜",
        "required_cost": "動画素材（引用）や英会話学習。",
        "reviews": { "クリエイターAI": "継続が命になるため、運用者の負担を下げる仕組み化が必要です。" },
        "score": 3, "status": "保留・次点",
        "updates": {}
    },
    {
        "id": "O",
        "title": "【政治・法律】「身近なトラブル・法律パペット解説」",
        "genre": "政治・法律",
        "platforms": ["YouTube", "X"],
        "persona": "日常生活での小さなトラブル（隣人トラブル、交通事故、労働基準）の対処法を知りたい一般層。",
        "approach": "パペット（人形）やVTuberのガワを使い、親しみやすく法律や政治家の政策の裏側を解説。",
        "reasoning": "難解な分野をエンタメ化することで競合を出し抜きやすい。法律事務所や保険の案件に誘導可能。",
        "estimated_revenue": "月12万円〜",
        "required_cost": "法律の正しい解釈のためのリサーチ費用、キャラクターデザイン費。",
        "reviews": { "リスクマネージャーAI": "不正確な情報発信は致命的なので、専門家監修が必要です。" },
        "score": 4, "status": "検証中",
        "updates": {}
    }
]

with open(r'c:\CreateApp\TrendFinder\data\strategies.json', 'w', encoding='utf-8') as f:
    json.dump(strategies, f, ensure_ascii=False, indent=2)

print(f"Generated {len(strategies)} strategies successfully.")
